name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
          - test
          - hack/tools
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          working-directory: ${{matrix.working-directory}}
